---
meta:
  environment: influxdb-nozzle-warden
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

name: influxdb-firehose-nozzle
director_uuid: PLACEHOLDER-DIRECTOR-UUID

compilation:
  workers: 1
  reuse_compilation_vms: true
  cloud_properties: {}

networks:
- name: influxdb-firehose-nozzle-net
  subnets:
    - range: 10.244.99.0/30
      reserved:
      - 10.244.99.1
      static: []
      cloud_properties: {}
    - range: 10.244.99.4/30
      reserved:
      - 10.244.99.5
      static: []
      cloud_properties: {}
    - range: 10.244.99.8/30
      reserved:
      - 10.244.99.9
      static: []
      cloud_properties: {}

jobs:
- name: influxdb-firehose-nozzle
  instances: 1
  networks:
  - name: influxdb-firehose-nozzle-net

resource_pools:
- name: influxdb-firehose-nozzle
  cloud_properties: {}

properties:
  loggregator:
    traffic_controller_url: wss://doppler.bosh-lite.com:4443
  influxdb:
  influxdb:
    db_url: 127.0.0.1
    db_database: database
    db_user: user
    db_password: "cloudc0w!"
    metric_prefix: cf.
  uaa:
    url: https://uaa.bosh-lite.com
    username: influxdb-firehose-nozzle
    password: influxdb-password
  nozzle:
    insecure_ssl_skip_verify: true
    subscription_id: influxdb-nozzle
    deployment: (( meta.environment ))
